languageCode = "en-IN"
defaultContentLanguage = "en"
publishDir = "docs"

enableEmoji = true
enableRobotsTXT = true
summaryLength = 0

baseURL = "https://debojitchanda.github.io/"

[pagination]
pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
