languageCode = "en-IN"
defaultContentLanguage = "en"
publishDir = "docs"

enableEmoji = true
enableRobotsTXT = true
paginate = 10
summaryLength = 0

baseURL = "https://debojitchanda.github.io/"


[outputs]
  home = ["HTML", "RSS", "JSON"]
