languageCode = "en"
languageName = "English"
displayName = ":flag-in"
isoCode = "en"
weight = 1
rtl = false

title = "Debojit"
#logo = "img/logo.jpg"
copyright = "&copy; 2025 Debojit Chanda"
description = "Personal website of Debojit Chanda"

dateFormat = "2 January 2006"

[params.author]
  name = "Debojit Chanda"
  image = "img/avatar.jpg"
  headline = "Contact Details"
  bio = "PMRF, IIT Kanpur"
  links = [
     { email = "mailto:dchanda@iitk.ac.in" },
     { google = "https://scholar.google.com/citations?user=FO7eN_gAAAAJ&hl=en" },
     { github = "https://github.com/debojitchanda" },
     { youtube = "https://www.youtube.com/channel/UCr327AE2Me4NzOKBgtKAV6A" },
     { map = "https://www.youtube.com/channel/UCr327AE2Me4NzOKBgtKAV6A" },
  ]
